### ISSUE TITLE
how can we get metadata from YFCC100M?

### ISSUE THREAD

**Issue by guanfuchen** [chi0tzp/YFCC100M-Downloader#1]
I see image and index, but which I can find the metadata containing the file description?

**Comment by guanfuchen** [comment]
I see it can just download first 1000 image directory, may it should support more.

**Comment by jinx2018** [comment]
Hi! I met the same problem, Could you tell what is the solution?

**Comment by yueliangjide** [comment]
> Hi! I met the same problem, Could you tell what is the solution?
Have you solved this problem?

**Comment by hefengwyh** [comment]
Hello! I met the problem too, I cannot find the annotations. Could you please tell me how can I get the annotations?
